service:
  name: surveyapi

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    SURVEY_USER_TABLE: ${self:custom.SurveyUsersTable.name}
    SURVEY_QUEST_TABLE: ${self:custom.SurveyQuestionsTable.name}
    SURVEY_RESPONSE_TABLE: ${self:custom.SurveyResponseTable.name}
  iamRoleStatements:
    - ${file(iam/QuestionsTableIAM.yml):QuestionsTableIAM}
    - ${file(iam/UsersTableIAM.yml):UsersTableIAM}
    - ${file(iam/ResponseTableIAM.yml):ResponseTableIAM}

resources:
  Resources:
    SurveyQuestionsTable: ${file(resources/SurveyQuestionsTable.yml):SurveyQuestionsTable}
    SurveyUsersTable: ${file(resources/SurveyUsersTable.yml):SurveyUsersTable}
    SurveyResponseTable: ${file(resources/SurveyResponseTable.yml):SurveyResponseTable}

functions:
  createQuestion:
    handler: src/handlers/createQuestion.handler
    events:
      - http:
          method: POST
          path: /question
          cors: true

  getQuestions:
    handler: src/handlers/getQuestions.handler
    events:
      - http:
          method: GET
          path: /questions
          cosrs: true

  getQuestionById:
    handler: src/handlers/getQuestionById.handler
    events:
      - http:
          method: GET
          path: /question/{id}
          cors: true

  getQuestionBySeq:
    handler: src/handlers/getQuestionBySeq.handler
    events:
      - http:
          method: GET
          path: /question/{id}/sequence
          cors: true

  userSurveyResponse:
    handler: src/handlers/users/userSurveyResponse.handler
    events:
      - http:
          method: POST
          path: /user/survey

  createUser:
    handler: src/handlers/createUser.handler
    events:
      - http:
          method: POST
          path: /user
          cors: true

  updatProfile:
    handler: src/handlers/users/updateProfile.handler
    events:
      - http:
          method: PATCH
          path: /user/{id}/profile
          cors: true
  getUserById:
    handler: src/handlers/getUserById.handler
    events:
      - http:
          method: GET
          path: /user/{id}
          cors: true

  addUserSurveyResponse:
    handler: src/handlers/users/addUserSurveyResponse.handler
    events:
      - http:
          method: PATCH
          path: /user/response
          cors: true

  updateSurveyStatus:
    handler: src/handlers/users/updateSurveyStatus.handler
    events:
      - http:
          method: PATCH
          path: /user/surveystatus
          cors: true

  newCognitoUser:
    handler: src/handlers/users/newCognitoUser.handler
    events:
      - cognitoUserPool:
          pool: ircocom60e2ad3e_userpool_60e2ad3e-dev
          trigger: PostConfirmation

custom:
  SurveyQuestionsTable:
    name: !Ref SurveyQuestionsTable
    arn: !GetAtt SurveyQuestionsTable.Arn
  SurveyUsersTable:
    name: !Ref SurveyUsersTable
    arn: !GetAtt SurveyUsersTable.Arn
  SurveyResponseTable:
    name: !Ref SurveyResponseTable
    arn: !GetAtt SurveyResponseTable.Arn
  bundle:
    linting: true
